### ISSUE TITLE
Relative Path issue with less.js

### ISSUE THREAD

**Issue by reggi** [less/less.js#1238]
Here's my directory structure

```
assets/
    components/
        bootstrap/
    stylesheets/
        bootstrap.less
        style.less
```

`bootstrap.less` looks like this

```
// CSS Reset
@import "../components/bootstrap/less/reset.less";

// Core variables and mixins
@import "../components/bootstrap/less/variables.less"; // Modify this for custom colors, font-sizes, etc
@import "../components/bootstrap/less/mixins.less";
```

It `@import`s each piece of bootstrap from the components folder. It's using relative the relative url with `../` to jump out of the current directory followed by `components/` to go into components.

The `style.less` file contains something like this.

```
@import "./bootstrap.less";
```

Which `@import`s this sibling file `boostrap.less`.

For some reason all of this isn't playing nicely with `less.js`

```
Couldn't load http://reggi.dev/reggi.com/assets/stylesheets/components/bootstrap/less/reset.less (404)
in bootstrap.less 
at http://reggi.dev/reggi.com/assets/components/less.js/dist/less-1.3.3.min.js:8:2505
at a (http://reggi.dev/reggi.com/assets/components/less.js/dist/less-1.3.3.min.js:8:3512)
at x (http://reggi.dev/reggi.com/assets/components/less.js/dist/less-1.3.3.min.js:8:3887)
at w (http://reggi.dev/reggi.com/assets/components/less.js/dist/less-1.3.3.min.js:8:1890)
at Function.r.Parser.importer (http://reggi.dev/reggi.com/assets/components/less.js/dist/less-1.3.3.min.js:8:22700)
at Object.m.imports.push (http://reggi.dev/reggi.com/assets/components/less.js/dist/less-1.3.3.min.js:8:9804)
at Object.e.Import (http://reggi.dev/reggi.com/assets/components/less.js/dist/less-1.3.3.min.js:9:6274)
at Object.p.parsers.import (http://reggi.dev/reggi.com/assets/components/less.js/dist/less-1.3.3.min.js:8:19029)
at E (http://reggi.dev/reggi.com/assets/components/less.js/dist/less-1.3.3.min.js:8:8091)
at Object.p.parsers.directive (http://reggi.dev/reggi.com/assets/components/less.js/dist/less-1.3.3.min.js:8:19845)
```

The path:

http://reggi.dev/reggi.com/assets/stylesheets/components/bootstrap/less/reset.less

Should be 

http://reggi.dev/reggi.com/assets/components/bootstrap/less/reset.less

---

I found this [ticket](https://github.com/cloudhead/less.js/pull/976) that has [SalimBensiali](https://github.com/SalimBensiali/less.js)'s less.js which didn't cause this error.

The problem with his version is that it's `1.3.0` which apparently doesn't support this which is in bootstrap:

```
.span@{index} { .span(@index); }
```

**Comment by JaKXz** [comment]
Is there any way to pass in the `relativeUrls` option to the `less.render` method in the node API?
