### ISSUE TITLE
modifyVars fails when using inline <style type="text/less">

### ISSUE THREAD

**Issue by moshen** [less/less.js#1599]
Here is a recreation of the issue using 1.4.1:
http://jsfiddle.net/jShpK/

The resulting stacktrace:

```
TypeError: Cannot read property 'href' of undefined
    at S (http://cdnjs.cloudflare.com/ajax/libs/less.js/1.4.1/less.min.js:9:3037)
    at http://cdnjs.cloudflare.com/ajax/libs/less.js/1.4.1/less.min.js:11:12931
    at Object.C [as _finish] (http://cdnjs.cloudflare.com/ajax/libs/less.js/1.4.1/less.min.js:9:11306)
    at Object.e.importVisitor.run (http://cdnjs.cloudflare.com/ajax/libs/less.js/1.4.1/less.min.js:11:4579)
    at Object.p.parse (http://cdnjs.cloudflare.com/ajax/libs/less.js/1.4.1/less.min.js:9:11377)
    at Object.r.modifyVars (http://cdnjs.cloudflare.com/ajax/libs/less.js/1.4.1/less.min.js:11:12886)
    at http://fiddle.jshell.net/jShpK/show/:28:10
    at jQuery.event.dispatch (http://code.jquery.com/jquery-2.0.2.js:4692:9)
    at elemData.handle (http://code.jquery.com/jquery-2.0.2.js:4376:28)
```

**Comment by lukeapage** [comment]
Hi,

sorry I didn't reply. Could we just keep the existing style tag? or do some browsers treat it as mangled css? Otherwise caching seems okay by me..

**Comment by matthew-dean** [comment]
Closing as no activity since 2015.

**Comment by himanshuwt** [comment]
Same error occurring again in the latest change/version.

**Comment by matthew-dean** [comment]
@himanshuwt What same error?

**Comment by himanshuwt** [comment]
@matthew-dean thank you for the response.

We're getting this error:

"TypeError: Cannot read property 'href' of undefined"

Stylesheet are not loading when browser have cookies.

**Comment by matthew-dean** [comment]
@himanshuwt Do you have a test repo? Since browser tests in Less are currently passing, there's no way to address this without a simplified test case.

**Comment by yangleyou** [comment]
There is no such problem when using version 1.50, but it appears again when using version 3.9.0
