### ISSUE TITLE
Installation missing modules

### ISSUE THREAD

**Issue by westhomas** [less/less.js#2347]
Attempting to install less yeild missing dependency 'promise' when I run lessc.

This is OSX Yosemite 10.10.1

```
$ sudo npm install -g less
npm WARN engine less@2.1.1: wanted: {"node":">=0.10.0"} (current: {"node":"0.8.20","npm":"2.1.14"})
/usr/local/bin/lessc -> /usr/local/lib/node_modules/less/bin/lessc
npm WARN unmet dependency /usr/local/lib/node_modules/karma/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/karma/node_modules/connect/node_modules/multiparty/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13-1
less@2.1.1 /usr/local/lib/node_modules/less
├── graceful-fs@3.0.5
├── mime@1.2.11
├── source-map@0.1.41 (amdefine@0.1.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── promise@6.0.1 (asap@1.0.0)
└── request@2.51.0 (caseless@0.8.0, oauth-sign@0.5.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, tunnel-agent@0.4.0, node-uuid@1.4.2, qs@2.3.3, mime-types@1.0.2, combined-stream@0.0.7, hawk@1.1.1, tough-cookie@0.12.1, http-signature@0.10.0, bl@0.9.3, form-data@0.2.0)

$ which lessc
/usr/local/bin/lessc

$ lessc

module.js:340
    throw err;
          ^
Error: Cannot find module 'promise'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/wes/.virtualenvs/nodeenv/lib/node_modules/less/lib/less-node/file-manager.js:3:59)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

**Comment by javierfigueroa** [comment]
This is definitely happening if I run npm install --production --no-optional  , when I use the no optional flag, I don't see promise getting installed by looking at npm's install output.

**Comment by lukeapage** [comment]
@javierfigueroa the promise issue is fixed on master and will be released very soon.
