### ISSUE TITLE
CLI: .bin shortcut is broken

### ISSUE THREAD

**Issue by am11** [less/less.js#2393]
I think this is a bug with v2.2.0.

```powershell
# this is powershell

mkdir /temp; cd /temp
npm install less
node node_modules/.bin/lessc
```

Throws:

```
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

Expected behavior was to get usage help.

**Comment by lukeapage** [comment]
Try
Node node_modules/less/bin/lessc

The file you are trying to run in node is a shell script to run node.
