### ISSUE TITLE
Got problem when installing LESS on Mac

### ISSUE THREAD

**Issue by gsm107** [less/less.js#2417]
when i type the "npm install less -g" in terminal, but it shows this:

module.js:340
    throw err;
          ^
Error: Cannot find module 'child-process-close'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/npm/lib/npm.js:15:1
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:474:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

I can't find solution for this problem.

**Comment by lukeapage** [comment]
Looks like an npm problem. Search for solutions and raise with them.

**Comment by matthew-dean** [comment]
You might try "npm install npm -g" first, in case a newer version of npm addresses the issue. See: https://docs.npmjs.com/misc/faq#how-do-i-update-npm-
