### ISSUE TITLE
less 2.3.1 and nodejs 0.10.35 bails if promise is missing

### ISSUE THREAD

**Issue by jbergstroem** [less/less.js#2422]
promise is according to package.json an [optional dependency](https://github.com/less/less.js/blob/master/package.json#L48), but when requiring less I get an exception about promise missing:
```
$ node a.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'promise'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/jbergstroem/Work/test/node_modules/less/lib/less-node/file-manager.js:3:59)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

$ cat a.js
var foo = require('less');
```

**Comment by lukeapage** [comment]
So, the Promise module is only optional if using a version of node with
uptodate v8 that includes native promises. I guess that version of node
doesnt? Should be a better error message though.

**Comment by lukeapage** [comment]
Although maybe this should be changed.. promises are optional since we
discovered they are forced async and less has a sync option. Pull request
welcome (move require promise into code block using it)

**Comment by jbergstroem** [comment]
@lukeapage Its still pretty rare with installations of nodejs that natively supports promises (0.11.x and iojs, I think neither is common outside of testing).
