### ISSUE TITLE
Unexpected token u in file undefined line no. undefined

### ISSUE THREAD

**Issue by elfet** [less/less.js#2452]
Got this error trying to compile bootstrap with gulp-less:
```
 ./node_modules/.bin/gulp
[11:36:31] Using gulpfile ~/Desktop/elfet.github.io/gulpfile.js
[11:36:31] Starting 'default'...
[11:36:31] Finished 'default' after 21 ms

/Users/anton/Desktop/elfet.github.io/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
SyntaxError: Unexpected token u in file undefined line no. undefined
    at Object.parse (native)
    at /Users/anton/Desktop/elfet.github.io/node_modules/gulp-less/node_modules/accord/lib/adapters/less.js:48:32
    at /Users/anton/Desktop/elfet.github.io/node_modules/gulp-less/node_modules/less/lib/less/render.js:35:17
    at /Users/anton/Desktop/elfet.github.io/node_modules/gulp-less/node_modules/less/lib/less/parse.js:63:17
    at Object.finish [as _finish] (/Users/anton/Desktop/elfet.github.io/node_modules/gulp-less/node_modules/less/lib/less/parser/parser.js:183:28)
    at Object.ImportVisitor._onSequencerEmpty (/Users/anton/Desktop/elfet.github.io/node_modules/gulp-less/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
    at ImportSequencer.tryRun (/Users/anton/Desktop/elfet.github.io/node_modules/gulp-less/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
    at Object.ImportVisitor.run (/Users/anton/Desktop/elfet.github.io/node_modules/gulp-less/node_modules/less/lib/less/visitors/import-visitor.js:29:25)
    at Object.Parser.parse (/Users/anton/Desktop/elfet.github.io/node_modules/gulp-less/node_modules/less/lib/less/parser/parser.js:189:22)
    at Object.parse (/Users/anton/Desktop/elfet.github.io/node_modules/gulp-less/node_modules/less/lib/less/parse.js:61:18)
```
What to do?
Here my gulpfile:
```
var gulp = require('gulp');
var less = require('gulp-less');
var sourcemaps = require('gulp-sourcemaps');
var autoprefixer = require('gulp-autoprefixer');
var minifyCSS = require('gulp-minify-css');
var uglify = require('gulp-uglify');
var concat = require('gulp-concat');
var path = require('path');

gulp.task('default', function () {
    gulp.src('src/less/*.less')
        .pipe(sourcemaps.init())
        .pipe(less({
            paths: [path.join(__dirname, 'less', 'includes')]
        }))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('css'));

    gulp.src(['src/css/*.css', 'vendor/highlight/style.css', '!src/css/print.css'])
        .pipe(autoprefixer({
            browsers: ['last 2 versions'],
            cascade: false
        }))
        .pipe(sourcemaps.init())
        .pipe(minifyCSS({keepBreaks: true}))
        .pipe(concat('main.css'))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('css'));

    gulp.src(['src/css/print.css'])
        .pipe(gulp.dest('css'));

    gulp.src(['bower_components/jquery/dist/jquery.js', 'src/js/*.js', 'vendor/highlight/highlight.js'])
        .pipe(sourcemaps.init())
        .pipe(uglify())
        .pipe(concat('main.js'))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('js'));

});
```

And bootstrap.less:
```
@charset "utf-8";

/* Bootstrap  */

@bootstrap: "../../bower_components/bootstrap/less";

// Core variables and mixins
@import "variables.less";
@import "@{bootstrap}/mixins.less";

// Reset and dependencies
@import "@{bootstrap}/normalize.less";
@import "@{bootstrap}/print.less";
//@import "@{bootstrap}/glyphicons.less";

// Core CSS
@import "@{bootstrap}/scaffolding.less";
@import "@{bootstrap}/type.less";
@import "@{bootstrap}/code.less";
@import "@{bootstrap}/grid.less";
@import "@{bootstrap}/tables.less";
@import "@{bootstrap}/forms.less";
@import "@{bootstrap}/buttons.less";

// Components
@import "@{bootstrap}/component-animations.less";
@import "@{bootstrap}/dropdowns.less";
@import "@{bootstrap}/button-groups.less";
@import "@{bootstrap}/input-groups.less";
@import "@{bootstrap}/navs.less";
@import "@{bootstrap}/navbar.less";
//@import "@{bootstrap}/breadcrumbs.less";
@import "@{bootstrap}/pagination.less";
//@import "@{bootstrap}/pager.less";
//@import "@{bootstrap}/labels.less";
//@import "@{bootstrap}/badges.less";
//@import "@{bootstrap}/jumbotron.less";
//@import "@{bootstrap}/thumbnails.less";
//@import "@{bootstrap}/alerts.less";
//@import "@{bootstrap}/progress-bars.less";
@import "@{bootstrap}/media.less";
//@import "@{bootstrap}/list-group.less";
//@import "@{bootstrap}/panels.less";
@import "@{bootstrap}/responsive-embed.less";
//@import "@{bootstrap}/wells.less";
@import "@{bootstrap}/close.less";

// Components w/ JavaScript
//@import "@{bootstrap}/modals.less";
//@import "@{bootstrap}/tooltip.less";
//@import "@{bootstrap}/popovers.less";
//@import "@{bootstrap}/carousel.less";

// Utility classes
@import "@{bootstrap}/utilities.less";
@import "@{bootstrap}/responsive-utilities.less";

/* =) */
```

**Comment by bassjobsen** [comment]
You have already posted your question at http://stackoverflow.com/questions/28513939/error-trying-to-compile-bootstrap-with-gulp-less too. SO seems the right place to post your question.

**Comment by lukeapage** [comment]
It looks like gulp is passing less "undefined" - I'd check your file paths

**Comment by mattez** [comment]
Hard reinstall of all node modules fix it in my case. Try:
* delete dir "node-modules"
* $npm cache clean
* $npm install
