### ISSUE TITLE
Error throw when saving a file.

### ISSUE THREAD

**Issue by DavidStrada** [less/less.js#2664]
Hey there!,

I keep having the same error after saving a file ( removed comments `// or /*  .... */` ) to test if that was causing some problem.

```
/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
TypeError: Cannot read property 'rules' of undefined
    at Import.eval (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/tree/import.js:140:46)
    at Ruleset.evalImports (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/tree/ruleset.js:188:36)
    at Ruleset.eval (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/tree/ruleset.js:96:17)
    at module.exports (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/transform-tree.js:66:22)
    at ParseTree.toCSS (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/parse-tree.js:14:25)
    at /Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/render.js:31:40
    at /Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/parse.js:63:17
    at Object.finish [as _finish] (/Users/macbook/Code/statamic/node_modules/gulp-less/node_modules/less/lib/less/parser/parser.js:183:28)
```

[ x ] I checked for circular dependencies ( none ).
[ x ] I saw an checked previous bug reports https://github.com/plus3network/gulp-less/issues/114 , https://github.com/less/less.js/issues/2430 reporting the same "bug".

If you need more info do let me know.

Thanks!

**Comment by seven-phases-max** [comment]
I don't think there's anything similar to either plus3network/gulp-less#114 or #2430.

Are you able to reproduce the same behaviour with `lessc`?

**Comment by DavidStrada** [comment]
Yes I can reproduce the same error running `lessc`

`css| on master⇒ lessc mesotheliomagroup.less > mesotheliomagroup.css
TypeError: Cannot read property 'rules' of undefined
    at Import.eval (/usr/local/lib/node_modules/less/lib/less/tree/import.js:140:46)
    at Ruleset.evalImports (/usr/local/lib/node_modules/less/lib/less/tree/ruleset.js:188:36)
    at Ruleset.eval (/usr/local/lib/node_modules/less/lib/less/tree/ruleset.js:96:17)
    at module.exports (/usr/local/lib/node_modules/less/lib/less/transform-tree.js:66:22)
    at ParseTree.toCSS (/usr/local/lib/node_modules/less/lib/less/parse-tree.js:14:25)
    at /usr/local/lib/node_modules/less/lib/less/render.js:31:40
    at /usr/local/lib/node_modules/less/lib/less/parse.js:63:17
    at Object.finish [as _finish] (/usr/local/lib/node_modules/less/lib/less/parser/parser.js:183:28)
    at Object.ImportVisitor._onSequencerEmpty (/usr/local/lib/node_modules/less/lib/less/visitors/import-visitor.js:35:14)
    at ImportSequencer.tryRun (/usr/local/lib/node_modules/less/lib/less/visitors/import-sequencer.js:50:14)`

**Comment by DavidStrada** [comment]
Lessc Version 

`css| on master!⇒ lessc --version
lessc 2.5.1 (Less Compiler) [JavaScript]`

**Comment by seven-phases-max** [comment]
>Yes I can reproduce the same error running  `lessc`

So posting the corresponding Less code (or its minimal version that is enough to reproduce the same error, e.g. just the offending import for example) would be handy.

**Comment by DavidStrada** [comment]
I have 6 import files on different locations ( lines )
line : 1 - 4
    @import "variables";
    @import (inline)"forms.min.css";
    @import (inline)"style.min.css";
    @import url( "@{main-font}" );

line: 2217-2218

    @import "close";
    @import "modals";

**Comment by seven-phases-max** [comment]
>line: 2217-2218

I see. Well, for us it will be somewhat impossible to create a test then to reproduce something like that (and to debug to find the problem). So the easiest way would be if you just upload your project somewhere if possible.

**Comment by seven-phases-max** [comment]
Closing due to inactivity.
