### ISSUE TITLE
lessc failes when called from node_modules/.bin

### ISSUE THREAD

**Issue by gka** [less/less.js#2689]
maybe this is a known issue, but I experienced this error when running `lessc` in `./node_modules/.bin/`:

```
node_modules/.bin/lessc src/style.less > build/style.css

module.js:340
   throw err;
         ^
Error: Cannot find module '../lib/less/fs'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous> (/path/to/project/node_modules/.bin/lessc:4:10)
   at Module._compile (module.js:456:26)
   at Object.Module._extensions..js (module.js:474:10)
   at Module.load (module.js:356:32)
   at Function.Module._load (module.js:312:12)
   at Function.Module.runMain (module.js:497:10)
make: *** [build/style.css] Error 8
```

when I run lessc from `./node_modules/less/bin` everything works fine.

Think this might be because `lessc` is using relative imports such as

```js
fs = require('../lib/less-node/fs')
```

**Comment by seven-phases-max** [comment]
Hmm, I wonder if `lessc` in `./node_modules/less/bin` is supposed to be used outside of that dir at all.
In fact when you install with `npm` (at least with `npm install -g less` in Windows), it creates *another* `lessc` script in `node` root dir:
```
#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/less/bin/lessc" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/less/bin/lessc" "$@"
  ret=$?
fi
exit $ret
```
I suppose *this* is the one you want to copy into `./node_modules/.bin/`.

**Comment by seven-phases-max** [comment]
Closing due to inactivity (and most likely expected behaviour).

**Comment by mfazul** [comment]
I am facing similar issue and using the docker to build the application.

Where should copy the script which is provided in the solution and what is the file name?
 Its urgent...
