### ISSUE TITLE
@import (inline) of remote file fails in 2.5.2

### ISSUE THREAD

**Issue by mkrauser** [less/less.js#2703]
This used to work with less v2.5.1, but fails in v2.5.2

```
@import (inline) url(https://fonts.googleapis.com/css?family=Lato);
```

This is the stack-trace of the error:
```
TypeError: Cannot read property 'reference' of undefined
    at Import.eval (...node_modules/less/lib/less/tree/import.js:131:122)
    at Ruleset.evalImports (...node_modules/less/lib/less/tree/ruleset.js:188:36)
    at Ruleset.eval (...node_modules/less/lib/less/tree/ruleset.js:96:17)
    at module.exports (...node_modules/less/lib/less/transform-tree.js:66:22)
    at ParseTree.toCSS (...node_modules/less/lib/less/parse-tree.js:14:25)
    at ...node_modules/less/lib/less/render.js:31:40
    at ...node_modules/less/lib/less/parse.js:63:17
    at Object.finish [as _finish] (...node_modules/less/lib/less/parser/parser.js:183:28)
    at Object.ImportVisitor._onSequencerEmpty (...node_modules/less/lib/less/visitors/import-visitor.js:35:14)
    at ImportSequencer.tryRun (...node_modules/less/lib/less/visitors/import-sequencer.js:50:14)
```

**Comment by lukeapage** [comment]
2.5.3 published with fix
