### ISSUE TITLE
Import with media query and sourcemap enabled emits error

### ISSUE THREAD

**Issue by RaveNoX** [less/less.js#2711]
Hello!
When compiling using `lessc --source-map-map-inline index.less` command following files

_index.less_
```less
.test {
 	color: #000;
 	@import "in.less" only screen and (min-width: 1024);
}
```

_in.less_
```less
a {
	color: #ccc;
}
```

Error emitted by lessc:
```
TypeError: Cannot read property 'substring' of undefined
    at SourceMapOutput.add (C:\Users\Fire\AppData\Roaming\npm\node_modules\less\lib\less\source-map-output.js:67:38)
    at Element.genCSS (C:\Users\Fire\AppData\Roaming\npm\node_modules\less\lib\less\tree\element.js:35:12)
    at Selector.genCSS (C:\Users\Fire\AppData\Roaming\npm\node_modules\less\lib\less\tree\selector.js:103:21)
    at Ruleset.genCSS (C:\Users\Fire\AppData\Roaming\npm\node_modules\less\lib\less\tree\ruleset.js:386:21)
    at Directive.outputRuleset (C:\Users\Fire\AppData\Roaming\npm\node_modules\less\lib\less\tree\directive.js:138:18)
    at Media.genCSS (C:\Users\Fire\AppData\Roaming\npm\node_modules\less\lib\less\tree\media.js:32:10)
    at Ruleset.genCSS (C:\Users\Fire\AppData\Roaming\npm\node_modules\less\lib\less\tree\ruleset.js:411:18)
    at SourceMapOutput.toCSS (C:\Users\Fire\AppData\Roaming\npm\node_modules\less\lib\less\source-map-output.js:118:24)
    at SourceMapBuilder.toCSS (C:\Users\Fire\AppData\Roaming\npm\node_modules\less\lib\less\source-map-builder.js:23:35)
    at ParseTree.toCSS (C:\Users\Fire\AppData\Roaming\npm\node_modules\less\lib\less\parse-tree.js:33:47)
```

Without `--source-map-map-inline` parameter compilation runs normally.

Last not affected version is 2.4.0.

**Comment by jasonverber** [comment]
This is likely related to https://github.com/less/less.js/pull/3360
