### ISSUE TITLE
Sourcemap generation fails on extend "all"

### ISSUE THREAD

**Issue by diagramatics** [less/less.js#2761]
I'm working with gulp-less and gulp-sourcemaps and I found out that extending all doesn't work with sourcemap generation.

```
&:extend(.clearfix all);
```

That's the particular line, and it throws this:

```
Potentially unhandled rejection [2] TypeError: Cannot read property 'substring' of undefined
    at [object Object].SourceMapOutput.add ([build]/node_modules/less/lib/less/source-map-output.js:67:38)
    at [object Object].Selector.genCSS ([build]/node_modules/less/lib/less/tree/selector.js:90:16)
    at [object Object].Ruleset.genCSS ([build]/node_modules/less/lib/less/tree/ruleset.js:371:25)
    at [object Object].Ruleset.genCSS ([build]/node_modules/less/lib/less/tree/ruleset.js:413:29)
    at [object Object].SourceMapOutput.toCSS ([build]/node_modules/less/lib/less/source-map-output.js:119:24)
    at [object Object].SourceMapBuilder.toCSS ([build]/node_modules/less/lib/less/source-map-builder.js:23:35)
    at [object Object].ParseTree.toCSS ([build]/node_modules/less/lib/less/parse-tree.js:33:47)
    at [build]/node_modules/less/lib/less/render.js:31:40
    at [build]/node_modules/less/lib/less/parse.js:63:17
    at Object.finish [as _finish] ([build]/node_modules/less/lib/less/parser/parser.js:183:28)
```

**Comment by hawkerboy7** [comment]
This appears to be an issue with with `gulp--less` / `gulp--sourcemaps`. You should post it there since it is not a problem of less itself. It works on the less2css page [example](http://lesscss.org/less-preview/#%7B%22less%22%3A%22.clearfix%20%7B%5Cn%5Ctzoom%3A%201%3B%5Cn%5Cn%5Ct%26%3Abefore%2C%5Cn%5Ct%26%3Aafter%20%7B%5Cn%5Ct%5Ctcontent%3A%20%5C%22%20%5C%22%3B%5Cn%5Ct%5Ctdisplay%3A%20table%3B%5Cn%5Ct%7D%5Cn%5Ct%26%3Aafter%20%7B%5Cn%5Ct%5Ctclear%3A%20both%3B%5Cn%5Ct%7D%5Cn%7D%5Cn%5Cn.test%20%7B%5Cn%5Ct%26%3Aextend(.clearfix%20all)%3B%5Cn%7D%22%7D)

**Comment by diagramatics** [comment]
@hawkerboy7 The stack trace shows that `less` is the problem. `gulp-less` only calls `render` and passes the `sourcemaps` option to it, so there's nothing extra that `gulp-less` does to tamper it. [Take a look](https://github.com/plus3network/gulp-less/blob/master/index.js#L37).

I don't think less2css has sourcemaps enabled.

**Comment by hawkerboy7** [comment]
@diagramatics Hi! Sorry you are right. I missed that part. I'll try to see if I can find anything!

**Comment by gigstada** [comment]
@diagramatics Do you have a reduced example case for this? I'm seeing this in a large application I'm working on but haven't been able to replicate it with a simple code example that I can share.
