### ISSUE TITLE
TypeError: [object Object] is not a function, it is object.

### ISSUE THREAD

**Issue by eximius313** [less/less.js#2765]
I have two environments: Windows 7 and GNU/Linux Debian Wheezy
I'm using Play Framework with sbt-less library.

On Windows machine my .less file compiles and runs just fine.
On Linux machine i get this exception:
```
[info] LESS compiling on 1 source(s)
[error] TypeError: [object Object] is not a function, it is object. (/home/users/project/project/project/target/node-modules/webjars/less/lib/less/index.js#4)    at /home/users/project/project/pr
oject/target/node-modules/webjars/less/lib/less/index.js:4
[error]     at /home/users/project/project/project/target/node-modules/webjars/less/lib/less-node/index.js:1
[error]     at module.js:456
[error]     at module.js:474
[error]     at module.js:356
[error]     at module.js:312
[error]     at module.js:364
[error]     at require (module.js:380)
[error]     at /home/users/project/project/project/target/node-modules/webjars/less/index.js:1
[error]     at module.js:456
[error]     at module.js:474
[error]     at module.js:356
[error]     at module.js:312
[error]     at module.js:364
[error]     at require (module.js:380)
[error]     at /home/users/project/project/project/target/less/sbt-less-1.1.0.jar:14
[error]     at /home/users/project/project/project/target/less/sbt-less-1.1.0.jar:3
[error]     at module.js:456
[error]     at module.js:474
[error]     at module.js:356
[error]     at module.js:312
[error]     at module.js:497
[error]     at startup (trireme.js:142)
[error]     at trireme.js:923
```

Could you please fix that?
Thank you in advance

**Comment by eximius313** [comment]
Previous error happens if I don't have pure Node.js installed and I'm using Trireme instead.
With Node.js error is slightly different:
```
[info] LESS compiling on 1 source(s)
[error]
[error] /home/users/project/project/project/target/node-modules/webjars/less/lib/less/index.js:13
[error]         functions: require('./functions')(environment),
[error]                                          ^
[error] TypeError: object is not a function
[error]     at module.exports (/home/users/project/project/project/target/node-modules/webjars/less/lib/less/index.js:13:42)
[error]     at Object.<anonymous> (/home/users/project/project/project/target/node-modules/webjars/less/lib/less-node/index.js:5:12)
[error]     at Module._compile (module.js:456:26)
[error]     at Object.Module._extensions..js (module.js:474:10)
[error]     at Module.load (module.js:356:32)
[error]     at Function.Module._load (module.js:312:12)
[error]     at Module.require (module.js:364:17)
[error]     at require (module.js:380:17)
[error]     at Object.<anonymous> (/home/users/project/project/project/target/node-modules/webjars/less/index.js:1:80)
[error]     at Module._compile (module.js:456:26)
```

**Comment by seven-phases-max** [comment]
I suppose the issue should be redirected to `sbt-less` (https://github.com/sbt/sbt-less?) library (and/or Play framework) - Less lib (i.e. the project in *this* repo) itself is known to run fine in properly installed `node` in either OS.

**Comment by eximius313** [comment]
ok, I have posted this issue there: https://github.com/sbt/sbt-less/issues/80

Kind regards
