### ISSUE TITLE
Using bin/lessc throws "Path must be a string. Received undefined" in node v6

### ISSUE THREAD

**Issue by jhnns** [less/less.js#2897]
As already reported in #2881 and [after merging](9500bfb734ee6e2e94b07b9c7f5dc8927ce22433)  #2891, running `lessc --source-map-map-inline styles/main.less` in node v6 throws 

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at /Users/jhnns/dev/jhnns/less.js/bin/lessc:311:61
    at Object.<anonymous> (/Users/jhnns/dev/jhnns/less.js/bin/lessc:508:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

This is because [an undefined path is passed as `basename`](https://github.com/less/less.js/blob/master/bin/lessc#L296).

**Comment by nktssh** [comment]
any updates regarding to this?

**Comment by mattecapu** [comment]
yes, I'd like to move to node@6 now that is LTS but I can't until this is fixed

**Comment by phillipchengh** [comment]
Wondering about the status of this? I get this error with node 6/7.

**Comment by pjotrvdh** [comment]
I'm getting this error as well..
How am I able to compile my less with an seperate map file?
I'm using the command:
`lessc --no-color test.less --source-map=test.css.map -source-map-url=test.css.map`

**Comment by jsguy** [comment]
As @jhnns mentioned, It turns out that it is looking for a 2nd parameter for the output (this is not documented), so this fails:
```bash
lessc --source-map=test.less.map test.less>test.css
```
However adding the output file as a parameter instead of piping it works:
```bash
lessc --source-map=test.less.map test.less ./test.css
```
Hope that helps you guys 👍

**Comment by seven-phases-max** [comment]
So, in other words, the proper fix would be "throw a error when sourcemap file is specified but the output css is not", right?
Obviously since the sourcemap *must* refer to a particular css file there's no (non-vulgar) methods to generate sourcemap w/o output css specified, i.e. these command lines simply make no sense:
```
lessc --source-map=test.less.map test.less
lessc --source-map=test.less.map test.less > test.css
```

**Comment by jsguy** [comment]
No, it should work like it used to - those two commands:

```bash
lessc --source-map=test.less.map test.less
lessc --source-map=test.less.map test.less > test.css
```

Should output this as the last line:

```javascript
/*# sourceMappingURL=test.less.map */
```

The CSS output file name is completely irrelevant, only the link to the map matters.

**Comment by seven-phases-max** [comment]
>The CSS output file name is completely irrelevant

Not quite, the sourcemap has the `file` field pointing to the output CSS (though I can see it's optional in the latests spec. revisions).

Either way, well, as far as I can tell the problem is in this [part](https://github.com/less/less.js/blob/v2.7.2/bin/lessc#L322). Thus it's just a matter of replacing the css output dir with whatever dir (sourcemap dir?) if `output` is not defined.
Well, PRs are wellcome (personally I don't use sourcemaps and have no idea what options can be broken by  these changes to test further).

**Comment by rjgotten** [comment]
How does it even make sense to generate an external source map and then pipe *only* the output css?

If anything further along in the pipe changes the output CSS in any way, it would invalidate the source map unless its additional mutations are tracked into another source map and both are merged.

However, anything further along in the pipe would not have any reference to the external source map, meaning it cannot do this for you.

Supporting external source maps together with piping has literally no functional value, other than the novelty and frivolity of allowing *nix users the convention of piping to a file rather than specifying an actual output parameter.

I would rather favor the clarity and user-guidance (e.g. 'falling into the pit of success') of disallowing a combination of operations that can only lead to problems with generated artifacts being broken.

**Comment by matthew-dean** [comment]
> Supporting external source maps together with piping offers no functional value. It only affords *nix users the convention of piping to a file rather than specifying an actual output parameter.

Agreed. If an output filename is to be specified, it should be specified as an argument to the `lessc` compiler.

**Comment by rjgotten** [comment]
> That said, was piping documented in the past?

PIping works by redirecting streams such as stdout or stderr.
When lessc is not given an output filename, it outputs into stdout.

In that sense, piping is officially supported and should continue to be supported. If you want to use it together with a source map you'd have to make it an inline source map and then rely on further processing steps in the pipe to decode it; modify it; and reapply it as an inline source map if the CSS is modified further by them.

Then, if you want an external source map for performance sake  -- I.e. avoiding the additional bytes of the inline map being delivered to all visitors. -- the final step in the pipeline should break the inline source map off and output two files: a css file and a map file.

**Comment by jeffawang** [comment]
>It makes no sense to generate an external source map and then pipe the output css to a further operation.
>
>Piping implies further changes happening in the next step(s) of the chain, or the CSS (and source map) being consumed to be served out by a web server application in the final step.

I disagree with the quoted sentiment, and I think it's incorrect to assume what's on the other side of any given pipe. What if the pipe is uploading to somewhere? What if the pipe is serving the resulting CSS, but the client doesn't always need the sourcemap? 

Seeing as the `--source-map-url` flag is implemented, I believe this use case should be supported.

In any case, users shouldn't be seeing inscrutable uncaught errors, especially when passing in flags from the help text.

Just my 2 cents after having been blocked by this issue.
