### ISSUE TITLE
Built-in functions are not available in certain contexts (impl. details).

### ISSUE THREAD

**Issue by seven-phases-max** [less/less.js#3054]
Example:
```less
@bar: pi();
@import "foo-@{bar}.less";
```
Result:
```
SyntaxError: Cannot read property 'get' of undefined in *.less on line 2, column 1
```
This happens because each context/frames has it's own copy of the functions set, but the set is copied there too late to be available for a (preeval only?) visitor (e.g. like the import visitor above). This obviously prevents any (preeval?) visitor to be able to evaluate any code that involves a function call.
Not sure if it still applies to the 3.x branch.

**Comment by calvinjuarez** [comment]
Output's a little different in 3.x, but it still errors.

```
$ lessc -v
lessc 3.0.0 (Less Compiler) [JavaScript]
$ lessc test.less test.css
TypeError: Cannot read property 'then' of undefined
    at parseLessFile (/Users/calvin/Sites/_contributing/less.js/bin/lessc:287:13)
    at /Users/calvin/Sites/_contributing/less.js/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```
_(using the same example)_

**Comment by seven-phases-max** [comment]
>Output's a little different in 3.x, but it still errors.

This is simply because `lessc` is broken after https://github.com/less/less.js/commit/b782411278a4916bec6ceaa4f6bb5cb56fd07620 (or so). Not really related to above issue.

**Comment by calvinjuarez** [comment]
Whoops, my bad.

**Comment by matthew-dean** [comment]
I assume this is fixed by https://github.com/less/less.js/commit/bad9be8a117a61942520059067833f13ddab9ef2 https://github.com/less/less.js/commit/94408424d6bd3e1dc85967094845ab1b8d420c30 ? (sorry for the dupe... my git skills still need improvement. Any help there is welcome.)

@seven-phases-max @calvinjuarez All tests should be passing now. At least they are locally. But AppVeyor / Travis are still saying things are broken, which I haven't had time to look into.

Otherwise, can you test the above code against alpha 3 and see if this issue can be closed?

**Comment by matthew-dean** [comment]
@seven-phases-max I just realized you said `lessc` was broken, which isn't covered by tests. We should add that as a to-do. To my knowledge, that's not actually tested anywhere.

**Comment by matthew-dean** [comment]
@seven-phases-max Was there a bug report I missed about `lessc` being broken?

**Comment by matthew-dean** [comment]
Possible dupe of #3112.

**Comment by matthew-dean** [comment]
Should this be closed? Still occurring?

**Comment by matthew-dean** [comment]
> This happens because each context/frame has its own copy of the functions set, but the set is copied there too late to be available for a (preeval only?) visitor (e.g. like the import visitor above). This obviously prevents any (preeval?) visitor to be able to evaluate any code involving a function call.

I took a look at this with a function called by a plugin. It definitely isn't eval'd in time, but this is beyond my current understanding of the Less tree. @seven-phases-max can you explain (as best you can) the way context/frames are defined within the Less engine? Maybe that could be documentation added to the code.

**Comment by seven-phases-max** [comment]
>Should this be closed? Still occurring?

Just try the initial example and if it fails then the issue is there.

>@seven-phases-max can you explain (as best you can) the way context/frames are defined within the Less engine? 

Uh... That would be not so easy. Personaly each time I had to deal with them I almost always went with `console.log(context.frames)` and then feeding the compiler with code of interest to see what I have there.
Basically `frames` is an array of objects representing all scopes from "the current" up to the top (the global) one. Thus `context` is a sort of "the state of the compiler" at the current point of execution like "scope (sort of 'pointer' to the current node in AST) + all the options + everything else".
[Example](https://github.com/seven-phases-max/less-plugin-reflections/blob/master/lib/main.js#L18) of traversing through frames to build the "parent selector list".
But I guess (by looking at all recent Less changes) you already get most of this on you own (so my apologizes for the late reply).
