### ISSUE TITLE
Circular `multiple` imports cause silent eternal loop

### ISSUE THREAD

**Issue by thybzi** [less/less.js#3058]
## Having two files:
_foo.less_
```less
@import (multiple) 'bar';
```
_bar.less_
```less
@import (multiple) 'foo';
```

## Running command:
```bash
lessc foo.less
```

## Expecting result (either):
* automatic loop resolve, or
* exiting with import loop exception

## Actual result:
Silent endless loop (ended only by Ctrl+C or JavaScript out-of-memory)

**Comment by seven-phases-max** [comment]
This makes sense (Though only *global* scope case can be safely stopped earlier. As, technically, I can create a non-infinite loop using such recursive imports. I.e. strictly speaking, it's not that really different from `while (true);` case).

**Comment by thybzi** [comment]
Stylus and Sass just throw something like 'Import loop detected' and exit. I believe it's much better than just freeze until the end of ~time~ js memory :)

**Comment by thybzi** [comment]
Of course, that shouldn't concern non-`multiple` imports. Their loop avoiding skills are just perfect in LESS :)

**Comment by seven-phases-max** [comment]
>Stylus and Sass just

:) Never works here. 
Not sure about Stylus but in Sass:
>It’s not possible to nest `@import` within mixins or control directives.

While in Less it is (so the detection is not that easy even inside ordinal rulesets as they may be guarded).

Either way I won't really object if a PR comes in, so just waiting for other opinions before setting a "ReadyForImplementatiion" label.

**Comment by thybzi** [comment]
> it's not that really different from indirect recursive function calls or just `while (true);`
Real use-cases are of course more complicated, the example I gave is a degenerate case.
So more correct comparison is `while ((a * b + c) > 0.75)`, where `a`, `b` and `c` are calculated and recalculated somewhere else.

**Comment by thybzi** [comment]
Not a proper place for discussing these, maybe, but:
_Sass_
```
$ sass circular/sass/_root.scss
Error: An @import loop has been found:
           circular/sass/_root.scss imports circular/sass/bar.scss
           circular/sass/bar.scss imports circular/sass/qux.scss
           circular/sass/qux.scss imports circular/sass/bar.scss
        on line 1 of circular/sass/qux.scss
        from line 1 of circular/sass/bar.scss
        from line 1 of circular/sass/_root.scss
  Use --trace for backtrace.
```
_Stylus:_
```
$ stylus circular/stylus/_root.styl
C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\bin\stylus:661
              throw err;
              ^

Error: circular/stylus/qux.styl:1:9
   1| @import 'bar';
--------------^
   2|
   3| .qux {
   4|     color: blue;

import loop has been found

    at Evaluator.importFile (C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:46:11)
    at Evaluator.visitImport (C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:920:27)
    at Evaluator.Visitor.visit (C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.importFile (C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:99:18)
    at Evaluator.visitImport (C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\lib\visitor\evaluator.js:920:27)
    at Evaluator.Visitor.visit (C:\Users\thybzi\AppData\Roaming\npm\node_modules\stylus\lib\visitor\index.js:28:40)
```

**Comment by thybzi** [comment]
Of course, I'll propose a PR if I'm able manage writing that code :)

**Comment by seven-phases-max** [comment]
Correcting myself:
> I can create a non-infinite loop using such recursive imports.

Actually I can't :) 
I.e. it's possible to create a recursive mixin or `.for` loop doing multiple imports of the same file but it does not need `(multiple)` because the import is actually happening at the point of the definition not at the point of expansion/valuation. And `(multiple)` recursion will be infinite no matter if it's guarded or not - thus detecting and  stopping recursive imports no matter where they are located indeed makes sense.

**Comment by matthew-dean** [comment]
Shouldn't this be marked as a bug?

**Comment by seven-phases-max** [comment]
Or a feature request. 
<sub>I usually put label "bug" only where something that supposed to work is not actually working (i.e. a clear error somewhere in the code). A proposal to improve some never specified / explicitly-defined behavior (or at least specify it) sounds like "feature request" (like in this case - it's not a error in the code but just an edge case that potentially can be handled in a more friendly way). Though this is pure linguistic thing, so please feel free to label it the way you feel to be right.</sub>

**Comment by matthew-dean** [comment]
@seven-phases-max Yeah, that makes sense it's a grey area if not actually specified. It could go either way.

**Comment by matthew-dean** [comment]
I think this is reasonable to mark as something that would be an accepted PR, as long as the loop detection is not too complex / adds a lot of code.
