### ISSUE TITLE
TypeError: Path must be a string. Received undefined @2.7.2

### ISSUE THREAD

**Issue by ugrg** [less/less.js#3117]
hello:
version:2.7.2
```sh
   lessc --no-color -ru --clean-css --source-map=index.map index.less
```
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:695:5)
    at D:\Program Files\nodejs\node_modules\less\bin\lessc:371:34
    at Object.<anonymous> (D:\Program Files\nodejs\node_modules\less\bin\lessc:615:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```
debug调试确认问题源头在less/bin/lessc
```
//  这里的output is undefined,可以使用||的方式修正这个错误
        if (options.sourceMap && !sourceMapFileInline)
        {
            var mapFilename = path.resolve(process.cwd(), sourceMapOptions.sourceMapFullFilename),
                mapDir = path.dirname(mapFilename),
                outputDir = path.dirname(output);
            // find the path from the map to the output file
            sourceMapOptions.sourceMapOutputFilename = path.join(
                path.relative(mapDir, outputDir), path.basename(output));

            // make the sourcemap filename point to the sourcemap relative to the css file output directory
            sourceMapOptions.sourceMapFilename = path.join(
                path.relative(outputDir, mapDir), path.basename(sourceMapOptions.sourceMapFullFilename));
        }
```
修改为:
```
        if (options.sourceMap && !sourceMapFileInline)
        {
            var mapFilename = path.resolve(process.cwd(), sourceMapOptions.sourceMapFullFilename),
                mapDir = path.dirname(mapFilename),
                outputDir = path.dirname(output || "./");
            // find the path from the map to the output file
            sourceMapOptions.sourceMapOutputFilename = path.join(
                path.relative(mapDir, outputDir), path.basename(output || "./"));

            // make the sourcemap filename point to the sourcemap relative to the css file output directory
            sourceMapOptions.sourceMapFilename = path.join(
                path.relative(outputDir, mapDir), path.basename(sourceMapOptions.sourceMapFullFilename));
        }
```

**Comment by matthew-dean** [comment]
Do you have a gist of the source file(s) used?

Please post issues in English or get help translating if possible.

**Comment by ugrg** [comment]
Hello:
I am not very good English, you now see these things I translated with google translation out.
Taking into account the language barriers, we still use the code as much as possible to describe the problem bars

My question is in the 2.7.2 version.
When i use it
```
lessc --no-color -ru --clean-css --source-map = index.map index.less
```
To compile CSS, the code will be error. The error is as follows:
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:695:5)
    at D:\Program Files\nodejs\node_modules\less\bin\lessc:371:34
    at Object.<anonymous> (D:\Program Files\nodejs\node_modules\less\bin\lessc:615:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```
I often try to debug your code and found in ./bin/lessc on options.sourceMap a code is not too strict, there is no non-empty verification for the output, so I suggest you add some adjustments here.

```
        if (options.sourceMap && !sourceMapFileInline)
        {
            //Add exception handling to output is undefined here
            output=output||"./";

            var mapFilename = path.resolve(process.cwd(), sourceMapOptions.sourceMapFullFilename),
                mapDir = path.dirname(mapFilename),
                outputDir = path.dirname(output);
            // find the path from the map to the output file
            sourceMapOptions.sourceMapOutputFilename = path.join(
                path.relative(mapDir, outputDir), path.basename(output));

            // make the sourcemap filename point to the sourcemap relative to the css file output directory
            sourceMapOptions.sourceMapFilename = path.join(
                path.relative(outputDir, mapDir), path.basename(sourceMapOptions.sourceMapFullFilename));
        }
```

**Comment by DisasterMan78** [comment]
I'm experiencing the same issue.

`lessc --source-map=awe.less.map --lists ${lessDir}/src/${lessEntryFile}.less > ${outputDir}/awe.css`

`(B[mTypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /usr/local/lib/node_modules/less/bin/lessc:322:34
    at Object.<anonymous> (/usr/local/lib/node_modules/less/bin/lessc:512:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)`

**Comment by seven-phases-max** [comment]
Closing as a duplicate of #2897.
