### ISSUE TITLE
Throws "TypeError: Cannot set property 'important' of undefined" when trying to compile

### ISSUE THREAD

**Issue by jonfiftyflowers** [less/less.js#3125]
Just updated to the latest stable version of Less (2.7.3) and I get this error when I try to compile our less. 
```
TypeError: Cannot set property 'important' of undefined
    at Array.<anonymous> (/usr/lib/node_modules/less/lib/less/tree/variable.js:31:42)
    at Variable.find (/usr/lib/node_modules/less/lib/less/tree/variable.js:48:17)
    at Variable.eval (/usr/lib/node_modules/less/lib/less/tree/variable.js:26:21)
    at Expression.eval (/usr/lib/node_modules/less/lib/less/tree/expression.js:31:37)
    at MixinCall.eval (/usr/lib/node_modules/less/lib/less/tree/mixin-call.js:59:30)
    at Ruleset.eval (/usr/lib/node_modules/less/lib/less/tree/ruleset.js:116:32)
    at Ruleset.eval (/usr/lib/node_modules/less/lib/less/tree/ruleset.js:149:50)
    at Ruleset.eval (/usr/lib/node_modules/less/lib/less/tree/ruleset.js:149:50)
    at module.exports (/usr/lib/node_modules/less/lib/less/transform-tree.js:67:22)
    at ParseTree.toCSS (/usr/lib/node_modules/less/lib/less/parse-tree.js:14:25)
```
It seems to be an issue with the parser or the less that is being compiled at that moment somehow relating to the ```!important``` css flag.

Any ideas on how to tackle this? Any suggestions or help are appreciated.

**Comment by matthew-dean** [comment]
Do you have a reduced test case where this issue happens?  2.7.3 shouldn't have introduced any critical changes.

**Comment by franck-grenier** [comment]
Same one on 2.7.2 and 2.7.3

**Comment by jonfiftyflowers** [comment]
I haven't been able to boil the issue down to a simple test case yet. You could say that I am dealing with a "complicated" less code base. 
I initially tried something like this:
```
#app {
  background: yellow;
  .color {
    background: black !important;
    height: 100px;
    width: 100%;
  }
}
```
This code compiles. 

The aforementioned error does not occur on versions before 2.7. I am also running node v8.8.1 if that helps. It appears that the problem has something to do with my code base and whatever changes were made in versions 2.7 of less onward. 

I am not sure exactly how to make a more useful test case because I am not 100% sure where the error is coming from inside my less code. I have seen issues filed in the past that are related to when you pass !important to a mixin like ```somemixin(attribute !important)``` but I don't believe anything like this is present in the less.

**Comment by fifty-git** [comment]
Finally got back to this and found the problem.

Someone had used `!important` in a variable definition
`@maxWidth: 1024px !important;`

Once I removed the `!important` the code compiled.

**Comment by matthew-dean** [comment]
This shouldn't be an issue as of 3.5 beta. Please re-open if `!important` causes this issue again.
